enable-magisk-update = true # set this to false if you do not want to receive updates for the module in magisk app
parallel-jobs = 1
cli-source = "MorpheApp/morphe-cli"
patches-source = "MorpheApp/morphe-patches"
rv-brand = "Morphe"

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[YouTube]
excluded-patches = ""
included-patches = ""
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"

[YouTube-Music]
arch = "arm64-v8a"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"
# uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"

[Reddit]
app-name = "Reddit"
apkmirror-dlurl = "https://www.apkmirror.com/apk/redditinc/reddit/"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.reddit.frontpage"
uptodown-dlurl = "https://reddit-official-app.en.uptodown.com/android"
dpi = "120-640dpi"


